SELECT
    TRIM(mois) AS mois,
    CAST(annee AS INT) AS annee,
    TRIM(trimestre) AS trimestre,
    CAST(effectif AS INT) AS effectif,
    CAST(nb_departs AS INT) AS nb_departs,
    CAST(nb_embauches AS INT) AS nb_embauches,
    CAST(taux_turnover_annuel AS FLOAT) AS taux_turnover_annuel,
    CAST(taux_turnover_mensuel AS FLOAT) AS taux_turnover_mensuel,
    TRIM(periode) AS periode,
    CAST(cout_recrutement_unitaire AS INT) AS cout_recrutement_unitaire,
    CAST(cout_formation_unitaire AS INT) AS cout_formation_unitaire,
    CAST(cout_indirect_unitaire AS INT) AS cout_indirect_unitaire,
    CAST(cout_turnover_mensuel AS INT) AS cout_turnover_mensuel,
    CAST(cout_recrutement_total AS INT) AS cout_recrutement_total,
    CAST(cout_formation_total AS INT) AS cout_formation_total,
    CAST(cout_indirect_total AS INT) AS cout_indirect_total,
    CAST(cout_total_mensuel AS INT) AS cout_total_mensuel,
    CAST(ca_moyen_employe_annuel AS INT) AS ca_moyen_employe_annuel,
    CAST(perte_productivite_pct AS FLOAT) AS perte_productivite_pct,
    CAST(perte_ca_estimee AS INT) AS perte_ca_estimee
FROM {{ source('entreprise','historique_mensuel_2020_2024') }}