    SELECT
        est_parti,
        niveau,
        age,
        anciennete_annees,
        salaire_annuel,
        salaire_median_departement,
        salaire_median_departement_niveau,
        salaire_moyen_departement,
        salaire_moyen_departement_niveau,
        performance,
        niveau_hierarchie,
        nb_promotions,
        nb_mobilites_internes,
        mois_depuis_derniere_promo,
        progression_salariale_pct,
        nb_formations_suivies,
        jours_absents_12mois,
        taux_absenteisme,
        sentiment_global,
        satisfaction_equipe,
        satisfaction_manager,
        culture_entreprise,
        equilibre_vie_pro_perso,
        opportunites_carriere,
        reconnaissance,
        nps_employeur,
        feedback_collegues,
        feedback_managers,
        cohesion_equipe,
        competences_techniques,
        soft_skills,
        leadership,
        communication,
        nb_feedbacks_recus
FROM  {{ ref('00_Table_individus') }}
WHERE employee_id IN ('EMP0075','EMP0441','EMP0359','EMP1136','EMP0572','EMP0122','EMP1025','EMP0225','EMP0696','EMP0301','EMP0297','EMP0611','EMP0651','EMP0099')


